name: pinboardfs
description: A FUSE filesystem for the Pinboard bookmarking service.
version: 0.0.1
homepage: https://github.com/maks/pinboardfs
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  pinboard: ^1.1.1
  dart_fuse:
    path: ../dart_fuse

dev_dependencies:
  pedantic: ^1.9.0
